### ISSUE TITLE
Web Socket Connectivity

### ISSUE THREAD

**Issue by aaronfranco** [telepat-io/telepat-worker#2]
Is it possible to connect to Telepat.io via websockets and listen to all updates on a specific channel/topic?

````
wss://IP_ADDRESS ... etc.
````

**Comment by Mayhem93** [comment]
The websockets connection is simple and only used to listen to two events: 
* **welcome** where the server will send you a socket ID (after which you need to update your device with this token)
* **message** where JSON-encoded data is received containing the updates.

In order to receive updates devices must subscribe to a certain channel of objects:

```
"channel": {
	"context": "context_Id",
	"model": "comment"
}
```
* This will subscribe you to all comments from that context (assuming your app has a model named **comment** and the context with that ID exists. Now every operation on comments in that context will be sent to you through webSockets notifications. Documentation: [ObjectSubscribe](http://docs.telepat.io/api.html#api-Object-ObjectSubscribe)

```json
{
  "data": {
    "new": [],
    "updated": [
      {
        "op": "increment",
        "value": 2,
        "path": "events/21f6f213-22cc-4209-9d5c-4ff1225b984c/counter",
        "channel": null,
        "email": null,
        "subscription": "blg:50ce3a5e-7a9a-465f-9567-8e5c38288f05:context:b90deebb-44b3-4fe1-9fc0-03fac7e242b6:events",
        "guid": "b0f35730-fcbf-448a-97fd-faef97c69c19",
        "ts": "2432668934168084",
        "application_id": "50ce3a5e-7a9a-465f-9567-8e5c38288f05",
        "context": "b90deebb-44b3-4fe1-9fc0-03fac7e242b6",
        "_microtime": 1446119826010391
      }
    ],
    "deleted": []
  }
}
```
* This is an example on the payload you would receive from the WebSockets connection.

These are some of the more technical details. The telepat clients (JS, Android, iOS) makes this much more easier to operate with.

I hope my answer covers your queries.

**Comment by aaronfranco** [comment]
okay, so if I should be able to connect to ws://IP_ADDRESS? Then I should see that message once I'm connected?

**Comment by Mayhem93** [comment]
I actually tried connecting with WebSockets (on Chrome) to the socket.io server but it doesn't work. Socket.io is an implementation of WebSockets. For this you have the socket.io client on the browser

**Comment by aaronfranco** [comment]
That's too bad. It would be cool if the Socket framework/library could be selected in configuration before startup. An implementation with https://github.com/primus/primus could allow for that. That would de-couple Telepat from the Socket.io framework. Food for thought :)

**Comment by Mayhem93** [comment]
Anyone can implement any type of transport and merge it with our branch. It's just that we never gotten to that point where plain WebSockets were a better choice than socket.io.

We might implement the **websockets_transport** worker. As long as people find use of this, we (and the community) can implement a lot of client transport systems.
