### ISSUE TITLE
Question on Horizontal Scaling

### ISSUE THREAD

**Issue by aaronfranco** [telepat-io/telepat-worker#3]
I'm wondering how the system is meant to scale. I can see multiple points of potential bottlenecks that would need to be addressed at high volume concurrency. The Node.js API would have to be behind a load balancer and scale horizontally. I take it that Zookeeper will automatically pick up on new Kafka instances as they are introduced. That being the case, then each type of worker would also have to be behind its own load balancer. The DB side would also have to scale. Is that accurate? Do new Kafka instances have to be manually added to the Zookeeper configuration? Are we meant to manually shard and grow the DB side of the platform, or is that automated somehow?

FYI: Loving this platform :+1:

**Comment by Mayhem93** [comment]
I don't know if I can fully answer your question but AFAIK kafka messages are sent in a round-robin fashion (when they are in the same group, in our case each type of workers have their own group), so they are basically balanced by the volume of messages kafka sends.

I don't know any details about RabbitMQ (the one we've used) but my guess is that it's the same.

I think @andreimarinescu can enlighten you better.

**Comment by aaronfranco** [comment]
Okay, so scaling the worker group behind a load balancer is correct? 
I don't understand how RabbitMQ fits considering it would replace Kafka. 

The website says "simple scaling," so I'm just trying to get my head around how it is intended to be scaled.

**Comment by Mayhem93** [comment]
The way I see the "simple scalling" part (speaking of workers) is that you can independently scale any **telepat** part (not talking about the other stuff, kafka, db's, etc).

* you got many iOS devices but few android devices? Add more *ios_transport* workers.
* more Android devices than iOS ? More *android_transport* workers.
* I, personally, have yet to discover a use case in which I had to scale *aggregation* and *write* workers in an unbalanced fashion in respect to eachother.
* More types of workers could be implemented which should scale in the same way.

Of course we won't/can't neglect the other "stuff", that's why we started with ElasticSearch (and couchbase 4.0 somewhere in the future), Kafka/AMQP which in my opinion scale easily.

**Comment by aaronfranco** [comment]
That all makes sense to me. Couchbase and Elasticsearch scale easily. I still don't see how RabbitMQ fits in.. I though all messaging was via Kafka?

**Comment by Mayhem93** [comment]
[telepat-models 0.2.5](https://github.com/telepat-io/telepat-models/releases/tag/v0.2.5): there's support for AMQP and Azure ServiceBus as alternatives to Kafka. We want people to have a good choice of messaging systems as well.

**Comment by aaronfranco** [comment]
cool :+1:
